---
# scope, level 1 only - this affects goss audits only
rhel9cis_level_1: true
rhel9cis_level_2: false

# fixed constraint, unlocks a cluster
# of level 1 controls that are off by default
rhel9cis_disruption_high: true

# warning banner
rhel9cis_warning_banner: "AIRNAV EXAM NODE - HANS - AUTHORIZED USE ONLY"

# PAM Faillock account lockout disabled
rhel9cis_rule_5_3_3_1_1: false
rhel9cis_rule_5_3_3_1_2: false
rhel9cis_rule_5_3_3_1_3: false

# authselect custom profile is set
# since it failed without this
rhel9cis_authselect_custom_profile_name: terminated_si_hans

rhel9cis_rule_1_2_2_1: false

# GNOME and GDM must survive hardening
rhel9cis_xwindow_server: true
rhel9cis_rule_2_1_20: false

# set gdm rules to false
rhel9cis_rule_1_8_1: false
rhel9cis_rule_1_8_2: false
rhel9cis_rule_1_8_3: false
rhel9cis_rule_1_8_4: false
rhel9cis_rule_1_8_5: false
rhel9cis_rule_1_8_6: false
rhel9cis_rule_1_8_7: false
rhel9cis_rule_1_8_8: false
rhel9cis_rule_1_8_9: false
rhel9cis_rule_1_8_10: false

# manually set level 2 rules to false
rhel9cis_rule_1_1_1_6: false
rhel9cis_rule_1_1_1_7: false
rhel9cis_rule_1_1_1_8: false
rhel9cis_rule_1_1_2_3_1: false
rhel9cis_rule_1_1_2_4_1: false
rhel9cis_rule_1_1_2_5_1: false
rhel9cis_rule_1_1_2_6_1: false
rhel9cis_rule_1_1_2_7_1: false
rhel9cis_rule_1_3_1_5: false
rhel9cis_rule_2_1_1: false
rhel9cis_rule_2_1_2: false
rhel9cis_rule_2_2_2: false
rhel9cis_rule_3_1_3: false
rhel9cis_rule_3_2_1: false
rhel9cis_rule_3_2_2: false
rhel9cis_rule_3_2_3: false
rhel9cis_rule_3_2_4: false
rhel9cis_rule_5_1_10: false
rhel9cis_rule_5_1_11: false
rhel9cis_rule_5_2_4: false
rhel9cis_rule_5_4_1_2: false
rhel9cis_rule_5_4_3_1: false
rhel9cis_rule_6_3_1_1: false
rhel9cis_rule_6_3_1_2: false
rhel9cis_rule_6_3_1_3: false
rhel9cis_rule_6_3_1_4: false
rhel9cis_rule_6_3_2_1: false
rhel9cis_rule_6_3_2_2: false
rhel9cis_rule_6_3_2_3: false
rhel9cis_rule_6_3_2_4: false
rhel9cis_rule_6_3_3_1: false
rhel9cis_rule_6_3_3_2: false
rhel9cis_rule_6_3_3_3: false
rhel9cis_rule_6_3_3_4: false
rhel9cis_rule_6_3_3_5: false
rhel9cis_rule_6_3_3_6: false
rhel9cis_rule_6_3_3_7: false
rhel9cis_rule_6_3_3_8: false
rhel9cis_rule_6_3_3_9: false
rhel9cis_rule_6_3_3_10: false
rhel9cis_rule_6_3_3_11: false
rhel9cis_rule_6_3_3_12: false
rhel9cis_rule_6_3_3_13: false
rhel9cis_rule_6_3_3_14: false
rhel9cis_rule_6_3_3_15: false
rhel9cis_rule_6_3_3_16: false
rhel9cis_rule_6_3_3_17: false
rhel9cis_rule_6_3_3_18: false
rhel9cis_rule_6_3_3_19: false
rhel9cis_rule_6_3_3_20: false
rhel9cis_rule_6_3_3_21: false
rhel9cis_rule_6_3_4_1: false
rhel9cis_rule_6_3_4_2: false
rhel9cis_rule_6_3_4_3: false
rhel9cis_rule_6_3_4_4: false
rhel9cis_rule_6_3_4_5: false
rhel9cis_rule_6_3_4_6: false
rhel9cis_rule_6_3_4_7: false
rhel9cis_rule_6_3_4_8: false
rhel9cis_rule_6_3_4_9: false
rhel9cis_rule_6_3_4_10: false

# enable goss audit
setup_audit: true
run_audit: true
fetch_audit_output: true
audit_output_destination: "./"
